name: Auto Bump Patch Version

on:
  push:
    branches:
      - main
        
permissions:
  contents: write 

jobs:
  auto-bump-patch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Fetch latest tags and bump patch
        run: |
          git fetch --tags
          LATEST_TAG=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
          echo "Latest semantic version tag is: $LATEST_TAG"

          if [ -z "$LATEST_TAG" ]; then
            echo "No existing semantic version tag found, starting from v0.0.1"
            NEW_TAG="v0.0.1"
          else
            VERSION=${LATEST_TAG#v}
            MAJOR=$(echo "$VERSION" | cut -d . -f 1)
            MINOR=$(echo "$VERSION" | cut -d . -f 2)
            PATCH=$(echo "$VERSION" | cut -d . -f 3)

            NEW_PATCH=$((PATCH + 1))
            NEW_TAG="v$MAJOR.$MINOR.$NEW_PATCH"
          fi

          echo "Creating new tag: $NEW_TAG"
          git tag "$NEW_TAG"
          git push origin "$NEW_TAG"